<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Workerman\\' => array($vendorDir . '/workerman/workerman'),
    'VoiceIt\\' => array($vendorDir . '/voiceit-php/voiceit2/voiceit'),
    'Tests\\' => array($vendorDir . '/rbdwllr/reallysimplejwt/tests'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Component\\Translation\\' => array($vendorDir . '/symfony/translation'),
    'Symfony\\Component\\Routing\\' => array($vendorDir . '/symfony/routing'),
    'Symfony\\Component\\HttpFoundation\\' => array($vendorDir . '/symfony/http-foundation'),
    'ReallySimpleJWT\\Helper\\' => array($vendorDir . '/rbdwllr/reallysimplejwt/src/Helper'),
    'ReallySimpleJWT\\Exception\\' => array($vendorDir . '/rbdwllr/reallysimplejwt/src/Exception'),
    'ReallySimpleJWT\\' => array($vendorDir . '/rbdwllr/reallysimplejwt/src'),
    'React\\Stream\\' => array($vendorDir . '/react/stream/src'),
    'React\\Socket\\' => array($vendorDir . '/react/socket/src'),
    'React\\Promise\\Timer\\' => array($vendorDir . '/react/promise-timer/src'),
    'React\\Promise\\' => array($vendorDir . '/react/promise/src'),
    'React\\EventLoop\\' => array($vendorDir . '/react/event-loop/src'),
    'React\\Dns\\' => array($vendorDir . '/react/dns/src'),
    'React\\Cache\\' => array($vendorDir . '/react/cache/src'),
    'Ratchet\\RFC6455\\' => array($vendorDir . '/ratchet/rfc6455/src'),
    'Ratchet\\' => array($vendorDir . '/cboden/ratchet/src/Ratchet'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'PHPSocketIO\\' => array($vendorDir . '/workerman/phpsocket.io/src'),
    'MyApp\\' => array($baseDir . '/src'),
    'Hhxsv5\\SSE\\' => array($vendorDir . '/hhxsv5/php-sse/src'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'Channel\\' => array($vendorDir . '/workerman/channel/src'),
    '' => array($vendorDir . '/nesbot/carbon/src'),
);
